#ifndef SDKCONFIG_H
#define SDKCONFIG_H

#define CONFIG_IDF_TARGET_WASM 1
#define CONFIG_STACKCHAN_FIRMWARE 1
#define FIRMWARE_VERSION "1.4.3-wasm"
#define CONFIG_MMAP_FILE_NAME_LENGTH 64
#define CONFIG_BOARD_TYPE_M5STACK_STACK_CHAN 1

#endif // SDKCONFIG_H
